### ISSUE TITLE
bug: Empty dependency

### ISSUE THREAD

**Issue by novacoole** [DataTables/Dist-DataTables-StateRestore-Bootstrap4#3]
in [`js/stateRestore.bootstrap4.mjs`,](https://github.com/DataTables/Dist-DataTables-StateRestore-Bootstrap4/blob/master/js/stateRestore.bootstrap4.mjs) there is an empty import: `import DataTable from '';`

This is preventing webpack compilation due to the empty dependency, i believe it should be `import DataTable from 'datatables.net-bs4';`

**Comment by AllanJard** [comment]
Thanks for letting me know about that. The base fix [is here](https://github.com/DataTables/StateRestore/commit/372567aa824ab8b49e5dabc7f26becedb3f99f47) and this repo was sync with that fix [here](https://github.com/DataTables/Dist-DataTables-StateRestore-Bootstrap4/commit/6d3f954575aac2b4ccf0f08132d2f2f37e484a1b).

I'll issue a new release with the fix soon.
